import Footer from "../../components/footer/footer";
import Navbar from "../../components/nav-bar/nav-bar";
import "./globals.css";
import { Prompt } from "next/font/google";

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Zentech Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={prompt.className}>
      <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
